import axios from "axios";
import { Bell, Check, LockKeyhole, Save, Shield, User } from "lucide-react";
import { useEffect, useState } from "react";

const Settings = () => {
  const user = JSON.parse(localStorage.getItem("user") || "null") as { id?: string; name?: string; email?: string } | null;
  const apiUrl = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
  const [profile, setProfile] = useState({ name: user?.name || "Ava Thompson", email: user?.email || "ava@northstarstudio.com", phone: "+1 415 555 0192" });
  const [notifications, setNotifications] = useState({ email: true, reminders: true, payments: true, marketing: false });
  const [saved, setSaved] = useState(false);
  const [twoFactor, setTwoFactor] = useState(false);

  const [error, setError] = useState("");
  useEffect(() => {
    if (!user?.id) return;
    axios.get<{ data: typeof profile }>(`${apiUrl}/auth/profile/${user.id}`).then((response) => setProfile(response.data.data)).catch(() => setError("Unable to load your profile"));
  }, [apiUrl, user?.id]);
  const saveSettings = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!user?.id) return; try { await axios.patch(`${apiUrl}/auth/profile/${user.id}`, profile); localStorage.setItem("user", JSON.stringify({ ...user, ...profile })); setSaved(true); setError(""); window.setTimeout(() => setSaved(false), 2500); } catch { setError("Unable to save your profile"); } };
  const toggleNotification = (key: keyof typeof notifications) => setNotifications((current) => ({ ...current, [key]: !current[key] }));

  return (
    <form onSubmit={saveSettings} className="space-y-7">
      <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Workspace preferences</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#183333] sm:text-4xl">Settings</h1><p className="mt-2 text-sm text-[#6c7b79]">Keep your profile, notifications, and account security up to date.</p></div><button type="submit" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#0f766e] px-4 py-3 text-sm font-bold text-white shadow-lg shadow-teal-900/15 hover:bg-[#115e59]"><Save className="h-4 w-4" /> Save changes</button></section>
      {saved && <div className="flex items-center gap-2 rounded-xl border border-[#b8e2d3] bg-[#dff3ec] px-4 py-3 text-sm font-bold text-[#0f766e]"><Check className="h-4 w-4" /> Your settings have been saved.</div>}
      {error && <div className="rounded-xl border border-[#f0d8ce] bg-[#fff0e9] px-4 py-3 text-sm font-bold text-[#b8583e]">{error}</div>}
      <div className="grid gap-6 xl:grid-cols-[1.35fr_.8fr]">
        <div className="space-y-6"><section className="rounded-2xl border border-[#dfeae4] bg-[#f8fbf9]/90 p-6 shadow-[0_14px_35px_rgba(31,69,63,.05)]"><div className="flex items-center gap-3 border-b border-[#e5eee9] pb-5"><div className="rounded-xl bg-[#dff3ec] p-2.5 text-[#0f766e]"><User className="h-5 w-5" /></div><div><h2 className="font-extrabold text-[#183333]">Profile information</h2><p className="text-xs text-[#82918d]">This appears on your workspace account.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="block text-xs font-bold text-[#6c7b79]">Full name<input value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} className="mt-2 w-full rounded-xl border border-[#dfeae4] bg-white px-4 py-3 text-sm text-[#183333] outline-none focus:border-[#0f766e]" /></label><label className="block text-xs font-bold text-[#6c7b79]">Phone number<input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} className="mt-2 w-full rounded-xl border border-[#dfeae4] bg-white px-4 py-3 text-sm text-[#183333] outline-none focus:border-[#0f766e]" /></label><label className="block text-xs font-bold text-[#6c7b79] sm:col-span-2">Work email<input type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} className="mt-2 w-full rounded-xl border border-[#dfeae4] bg-white px-4 py-3 text-sm text-[#183333] outline-none focus:border-[#0f766e]" /></label></div></section>
          <section className="rounded-2xl border border-[#dfeae4] bg-[#f8fbf9]/90 p-6 shadow-[0_14px_35px_rgba(31,69,63,.05)]"><div className="flex items-center gap-3 border-b border-[#e5eee9] pb-5"><div className="rounded-xl bg-[#fff0e9] p-2.5 text-[#d96e50]"><Bell className="h-5 w-5" /></div><div><h2 className="font-extrabold text-[#183333]">Notification preferences</h2><p className="text-xs text-[#82918d]">Choose what your team should hear about.</p></div></div><div className="mt-2 divide-y divide-[#e5eee9]">{([ ["email", "Email notifications", "Updates about new bookings"], ["reminders", "Appointment reminders", "Automatic client reminders"], ["payments", "Payment updates", "Successful and failed payments"], ["marketing", "Product updates", "News and feature announcements"] ] as const).map(([key, label, description]) => <div key={key} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-bold text-[#183333]">{label}</p><p className="mt-1 text-xs text-[#82918d]">{description}</p></div><button type="button" onClick={() => toggleNotification(key)} aria-label={`Toggle ${label}`} className={`relative h-6 w-11 shrink-0 rounded-full transition ${notifications[key] ? "bg-[#0f766e]" : "bg-[#cbd8d3]"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${notifications[key] ? "left-6" : "left-1"}`}></span></button></div>)}</div></section>
        </div>
        <div className="space-y-6"><section className="rounded-2xl bg-[#163d42] p-6 text-white shadow-[0_18px_40px_rgba(16,47,53,.18)]"><div className="flex items-center gap-3"><div className="rounded-xl bg-white/10 p-2.5 text-[#8ed0bd]"><Shield className="h-5 w-5" /></div><div><h2 className="font-extrabold">Security</h2><p className="text-xs text-[#8ebdb1]">Protect your account.</p></div></div><div className="mt-6 space-y-3"><button type="button" className="flex w-full items-center gap-3 rounded-xl bg-white/10 px-4 py-3 text-left text-sm font-bold text-white hover:bg-white/15"><LockKeyhole className="h-4 w-4 text-[#8ed0bd]" /> Change password</button><button type="button" onClick={() => setTwoFactor(!twoFactor)} className="flex w-full items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-left text-sm font-bold text-white hover:bg-white/15"><span className="flex items-center gap-3"><Shield className="h-4 w-4 text-[#8ed0bd]" /> Two-factor authentication</span><span className="text-xs text-[#f2b49f]">{twoFactor ? "On" : "Off"}</span></button></div></section><section className="rounded-2xl border border-[#dfeae4] bg-[#f8fbf9]/90 p-6"><p className="text-xs font-extrabold uppercase tracking-wider text-[#82918d]">Plan and billing</p><h2 className="mt-2 text-lg font-extrabold text-[#183333]">Professional workspace</h2><p className="mt-2 text-sm leading-6 text-[#6c7b79]">Unlimited appointments, client profiles, and payment tracking for your team.</p><button type="button" className="mt-5 w-full rounded-xl border border-[#0f766e] py-3 text-sm font-extrabold text-[#0f766e] hover:bg-[#dff3ec]">Manage billing</button></section></div>
      </div>
    </form>
  );
};

export default Settings;
